name: multilizely
description:
  A Command Line Interface for working with Localizely in flutter projects
  that contain multiple l10n.yaml files.
version: 0.0.2
repository: https://github.com/videostage/multilizely
issue_tracker: https://github.com/videostage/multilizely/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  yaml: ^3.1.1
  args: ^2.3.1
  equatable: ^2.0.3
  dio: ^4.0.0

executables:
  multilizely:
